DELETE FROM marketplace_products;

INSERT INTO marketplace_products (
    product_id, title, short_description, description,
    price, currency, product_type, pricing_type, pricing_modes,
    price_per_hour, price_per_day, price_per_week, price_per_month, price_per_session,
    seller_id, seller_type, seller_name, seller_picture_url,
    category, subcategory, cover_image_url, image_url, image_urls,
    condition_label, included_items, size_dimensions,
    available_quantity, in_stock, deposit_required, deposit_amount,
    pickup_type, pickup_notes, availability_note, return_rules, cancellation_rules,
    city, lat, lng, location_address_raw, location_privacy, radius_km,
    related_spotyou_ids, tag_ids, delivery_modes,
    status, skill_level, rejection_reason, admin_comment,
    brand, model, weight, stripe_product_id, stripe_price_id,
    created_at, updated_at
) VALUES
('prod_s39_owner_001', 'Velo gravel', 'Gravel alu', 'Description du vélo gravel qui contient plus de trente caractères.',
 45.00, 'EUR', 'rental', 'day', '["day","week"]',
 NULL, 45.00, 250.00, NULL, 30.00,
 'user_private001', 'user', 'Marie Martin', NULL,
 'sport', 'bike', 'https://img/s39/cover1.jpg', 'https://img/s39/cover1.jpg', '["https://img/s39/cover1.jpg","https://img/s39/2.jpg"]',
 'good', 'casque', '54cm',
 2, TRUE, TRUE, 120.00,
 'local_pickup', 'Paris 12', 'Disponible weekend', 'retour propre', 'annulation 24h',
 'Paris', 48.8566, 2.3522, '10 rue test', '100m', 0.1,
 '["tp_001"]', '["tag_endurance"]', '["local_pickup"]',
 'draft', 'tous', NULL, NULL,
 'Trek', 'Domane', '9.2', NULL, NULL,
 TIMESTAMP WITH TIME ZONE '2026-05-01 10:00:00+00:00', TIMESTAMP WITH TIME ZONE '2026-05-01 10:00:00+00:00'),
('prod_s39_owner_002', 'Tapis yoga', 'Tapis 6mm', 'Description longue du tapis yoga avec suffisamment de détails pour dépasser 30 caractères.',
 39.90, 'EUR', 'sale', 'fixed', '["sale"]',
 NULL, NULL, NULL, NULL, NULL,
 'user_private001', 'user', 'Marie Martin', NULL,
 'sport', 'yoga', 'https://img/s39/cover2.jpg', 'https://img/s39/cover2.jpg', '["https://img/s39/cover2.jpg"]',
 'new', NULL, NULL,
 1, TRUE, FALSE, NULL,
 'creator_handoff', NULL, NULL, NULL, NULL,
 'Paris', NULL, NULL, NULL, '100m', 0.1,
 '[]', '["tag_hatha"]', '["creator_handoff"]',
 'active', 'tous', NULL, NULL,
 NULL, NULL, NULL, NULL, NULL,
 TIMESTAMP WITH TIME ZONE '2026-05-02 10:00:00+00:00', TIMESTAMP WITH TIME ZONE '2026-05-02 10:00:00+00:00'),
('prod_s39_other_001', 'Produit autre', 'Autre', 'Description longue appartenant à un autre vendeur pour test ownership.',
 25.00, 'EUR', 'rental', 'day', '["day"]',
 NULL, 25.00, NULL, NULL, NULL,
 'user_demo001', 'user', 'Thomas Dupont', NULL,
 'sport', 'other', NULL, NULL, '[]',
 'good', NULL, NULL,
 1, TRUE, FALSE, NULL,
 'local_pickup', NULL, NULL, NULL, NULL,
 'Paris', NULL, NULL, NULL, '100m', 0.1,
 '[]', '["tag_endurance"]', '["local_pickup"]',
 'active', 'tous', NULL, NULL,
 NULL, NULL, NULL, NULL, NULL,
 TIMESTAMP WITH TIME ZONE '2026-05-03 10:00:00+00:00', TIMESTAMP WITH TIME ZONE '2026-05-03 10:00:00+00:00');
