-- Socle Flyway : première migration neutre (PostgreSQL / tests H2 compatible).
CREATE TABLE IF NOT EXISTS schema_migration_marker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
