ALTER TABLE marketplace_products
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS media_purge_scheduled_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS media_purge_notified_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS media_purged BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS media_purged_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS reactivated_at TIMESTAMP WITH TIME ZONE;
